about(contextPath)::="
<!-- Begin page content -->
<div class='container'>
	<div class='page-header'>
    	<h1>About Us</h1>
  	</div>
  	<p class='lead'>
  		Falcon Town Car Transportation is a unique chauffeured transportation service that operates limousines, Lincoln Town Cars, 
  		various luxury SUV's, vans and coaches, and has been serving the Greater Seattle area for the past two decades. At Seattle Falcon 
  		Towncar we consider ourselves your personal staff. When you choose Seattle Falcon Towncar Transportation services you are choosing 
  		personalized service of the highest caliber. 
  	</p>
  	<p class='lead'>
  		You are choosing to be cared for by an expert team, dedicated to serving your each and every need - a team large enough to 
  		accommodate the full complement of services one should expect from a major luxury transportation firm, but committed enough 
  		to recognize that you are the only customer who matters.
  	</p>
  	
  	<p class='lead'>
  		Please feel free to contact us at any time. We operate twenty four hours a day, seven days a week, three hundred and sixty five days a year.
  	</p>
  
	<div class='page-header'>
    	<h1>Customer Satifaction</h1>
  	</div>
  	<p class='lead'>
  		Please feel free to call us if you have any questions. We are committed to metting and exeeding our clients expectations.
  	</p>
  	<p class='lead'>
  		Seattle Falcon Town Car Service in Seattle wants you to expect a worry free, simple and straightforward approach, to 
  		ensure that we are your one and only personal chauffer service in Seattle.
  	</p>
</div>
";