contact(contextPath)::="
<!-- Begin page content -->
<div class='container'>
	<div class='page-header'>
    	<h1>Contact Us</h1>
  	</div>
  	<p class='lead'>
  		Falcon Towncar Transportation operates 24 hours, 7 days a week, 365 days a year.
		Please feel free to contact us at any time. <br/><br/>
	
		Phone: (206) 371-6461 <br/>
		Fax: (425) 981-0031 <br/>
		Email: Reservations@FalconTowncar.com
  	</p>
  
  	<div class='page-header'>
    	<h1>New Customer</h1>
  	</div>
  	<p class='lead'>
  		The most effective method of requesting a quote is to submit an accurate 
  		Reservation Form. If you would rather speak with a representative please feel free to call us at (206) 371-6461.
  	</p>
  
  	<div class='page-header'>
    	<h1>Airport Arrivals</h1>
  	</div>
  	<p class='lead'>
  		If you have scheduled a pick-up: Once you locate your luggage, please walk to the nearest exit, take note of 
  		the gate number and call us at (206) 371-6461. Gate Numbers are located above each exit door.
	</p>
	
	<p class='lead'>
		If you are arriving into Sea-Tac(Seattle) and have not yet made a reservation, please submit a Reservation 
		Form or Call us at (206) 371-6461 at least 24 hours in advance. We also offer short-notice pick-ups but please 
		be aware that waiting time may be upwards of 30 minutes.
  	</p>
  	
  	<div class='page-header'>
    	<h1>Cruise Transfers</h1>
  	</div>
  	<p class='lead'>
  		Falcon Towncar offers cruise transfer services to all cruise lines in the greater Seattle area. Please feel 
  		free to call or email us to today to request a transfer. Competitive rates are available for both, Sea-Tac 
  		Airport and Seattle Hotel cruise transfers.
  	</p>
</div>
";