registration(contextPath)::="
<!-- Begin page content -->
<div class='container'>
  <div class='page-header'>
    <h1>Registration</h1>
  </div>
	<form>
		First name: <input type="text" name="firstname"><br>
		Last name: <input type="text" name="lastname"><br>
		Email: <input type="text" name="email"><br>
		Password: <input type="password" name="pwd"><br>
		Confirm Password: <input type="text" name="email"><br>
		Phone Number: input type="text" name="phone"><br><br>
		
		<input type="submit" value="Submit">
	</form>
</div>
";