signup()::="
<div class='container'>
	<div class='jumbotron'>
		<h1 align='center'>Sign Up</h1><br/>
		<form class='form-horizontal' role='form'>
		  <div class='form-group'>
		    <label for='inputEmail3' class='col-sm-2 control-label'>Email</label>
		    <div class='col-sm-10'>
		      <input type='email' class='form-control' id='inputEmail3' placeholder='Email'>
		    </div>
		  </div>
		  <div class='form-group'>
		    <label for='inputPassword3' class='col-sm-2 control-label'>Password</label>
		    <div class='col-sm-10'>
		      <input type='password' class='form-control' id='inputPassword3' placeholder='Password'>
		    </div>
		  </div>
		   <div class='form-group'>
		    <label for='inputPasswordConfirm' class='col-sm-2 control-label'>Confirm Password</label>
		    <div class='col-sm-10'>
		      <input type='password' class='form-control' id='inputPasswordConfirm' placeholder='Confirm Password'>
		    </div>
		  </div>
		  <div class='form-group'>
		    <div class='col-sm-offset-2 col-sm-10'>
		      <div class='checkbox'>
		        <label>
		          <input type='checkbox'> Remember me
		        </label>
		      </div>
		    </div>
		  </div>
		  <div class='form-group'>
		    <div class='col-sm-offset-2 col-sm-10'>
		      <button type='submit' class='btn btn-default'>Submit</button>
		      <button type='reset' class='btn btn-default'>Reset</button>
		    </div>
		  </div>
		</form>
	</div>
</div>
";