termsandconditions(contextPath)::="

<div class='title'>
  <div class='container'>
    <section class='title-section'>
      <h1 class='title-header'>Terms and Conditions</h1>
    </section>
  </div>
</div>

<div class='container'>
  	<div class='page-header'>
  		<h3>General</h3>
  	</div>
  	<p class='lead'>
  		We request you book your reservations at least 24 hours in advance. Under normal circumstances reservations can be 
  		made with as little as one hour notice and is subject to availability. Requests for online reservations must be made 
  		at least 24 hours in advance, for reservations less than 12 hours call (206) 371-6461, 24 hours a day to make, 
  		change or cancel reservations. Falcon Towncar Transportation shall not be liable for delays or services not rendered 
  		due to circumstances beyond its control including but not limited to severe weather, road conditions and vehicle breakdowns. 
  		All published rates are subject to change without notice. Current rates are confirmed at the time a reservation is made. 
  		Specialty vehicle requests are subject to availability at the time of booking. All content provided is copyrighted by Falcon 
  		Towncar Transportation, its affiliates or partners. The information presented and this website is maintained for your personal 
  		use and information. You may not alter, redistribute, copy, send, display, reproduce, publish, and transfer anything 
  		including information, software or services obtained from this website without the written permission of Falcon Towncar 
  		Transportation. Falcon Towncar Transportation reserves the right to modify these conditions at any time.  
  	</p>
  	
  	<div class='page-header'>
  		<h3>Cancellation Policy</h3>
  	</div>
  	<p class='lead'>
		There is a two 2 hour cancellation policy for orders. You can cancel a reservation 2 hours before the pickup time 
		with no charge. You must contact us by phone! Orders changed or cancelled less than 2 hours before pick-up time will be 
		charged at full rate plus 20% gratuity due to loss of revenue and dead time for cars and chauffeurs. A 48-hour 
		cancellation policy applies to all charter and specialty vehicle reservations. 
  	</p>
  	
  	<div class='page-header'>
  		<h3>No Show Policy</h3>
  	</div>
  	<p class='lead'>
		50% of the fare will also be charged if the passenger fails to be at the designated pickup location. 
		We do not guarantee vehicle availability or pricing for any reservation changes but we will work with you to 
		provide the best solution. If you cannot locate your car, please do not leave your location without contacting us by phone at (206) 371-6461.  
  	</p>
  	
  	<div class='page-header'>
  		<h3>Payment Policy</h3>
  	</div>
  	<p class='lead'>
		Trips can be billed to the customer's credit card or corporate account numbers. Falcon Towncar Transportation 
		accepts the following credit cards: American Express, Visa, MasterCard, Discover Card. You can also pay cash. 
		At this time we do not accept checks, gift cards or any other form of payment not stated above. All reservations 
		are subject to a guaranteed payment. A credit card number will be taken to secure the reservation but we will charge 
		it only after we provide you with service.  
  	</p>
  	
  	<div class='page-header'>
  		<h3>Early-late hours and holiday policy</h3>
  	</div>
  	<p class='lead'>
		A premium rate of \$15.00 applies to the following: Daily: Between the hours of 11:00 pm and 5:00 am Holidays: 
		4th of July, Labor Day, Thanksgiving Day, Christmas Eve, Christmas Day, New Years Eve and New Years Day.   
  	</p>
  	
  	<div class='page-header'>
  		<h3>Waiting time policy</h3>
  	</div>
  	<p class='lead'>
		There is a 15-minute grace period from your scheduled pick-up time. After the grace period has elapsed, there is a charge of \$15.00 for every 15 minutes.   
  	</p>
  	
  	<div class='page-header'>
  		<h3>Additional stops policy</h3>
  	</div>
  	<p class='lead'>
		For each extra stop a fee of \$10 will apply. This means that if you need to pick up somebody else that you travel with, 
		in your way to the airport a \$10 fee will be added to your rate.    
  	</p>
  	
  	<div class='page-header'>
  		<h3>No Smoking Policy</h3>
  	</div>
  	<p class='lead'>
		All of our cars are non-smoking. Client agrees that there will be no smoking in our vehicle(s).     
  	</p>
  	
  	<div class='page-header'>
  		<h3>Pickup Time Disclaimer</h3>
  	</div>
  	<p class='lead'>
		Selecting a pickup time later than what is recommended could result in missing a flight or appointment. Falcon Towncar Transportation 
		can NOT be held responsible, and reservation will be marked as Time Requested by Customer.      
  	</p>
  	
  	<div class='page-header'>
  		<h3>Acceptance of terms and conditions</h3>
  	</div>
  	<p class='lead'>
		Client has read the terms and conditions stated above and agree to all stated terms and conditions. This agreement will be 
		considered accepted in its entirety when Client checks the \"I Agree\" box provided in the Online Reservation - Booking Form of this Web site.      
  	</p>
  	
  	<div class='page-header'>
  		<h3>Privacy Policy</h3>
  	</div>
  	<p class='lead'>
		Falcon Towncar Transportation respects your privacy and your name and personal information will not be given to anyone without your consent. 
		The information you supply is used to improve service and customize offers for you. Your name and address will only be used by Falcon 
		Towncar Transportation or its assignees for the purpose of rendering service or to collect payments for services rendered. Your e-mail 
		address is used for sending confirmations, information and service enhancements.      
  	</p>
</div>
";